name: Build and Release macOS Executable

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v0.1.0, etc.
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest  # Run the job on a macOS environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up Python from Pipfile
        id: setup_python
        run: |
          python -c "import toml; print(toml.load('Pipfile')['default']['python_version'])" > python_version.txt
          echo "Python version is $(cat python_version.txt)"
          echo "::set-output name=python_version::$(cat python_version.txt)"
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.setup_python.outputs.python_version }}  # Get the version from the previous step

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv  # Ensure Pipenv is installed
          pipenv install  # Install dependencies (including PyInstaller)

      - name: Build with PyInstaller
        run: |
          pipenv run pyinstaller --onefile --windowed --icon=app.ico src/main.py
          
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main.app

      - name: Upload the release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main.app  # The uploaded archive for release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate API requests
     
